name       : faad
version    : 2.8.8
release    : 7
source     :
    - https://sourceforge.net/projects/faac/files/faad2-src/faad2-2.8.0/faad2-2.8.8.tar.gz/download : 985c3fadb9789d2815e50f4ff714511c79c2710ac27a4aaaf5c0c2662141426d
homepage   : http://www.audiocoding.com/downloads.html
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : Open source MPEG-2 and MPEG-4 AAC decoder
description: |
    Freeware Advanced Audio (AAC) Decoder is a HE, LC, MAIN and LTP
    profile, MPEG-2 and MPEG-4 AAC decoder. FAAD2 includes code for SBR
    (HE AAC) decoding.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/faad2-2.8.3-libmp4ff-shared-lib.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install

