name       : faad
version    : 2.9.2
release    : 10
source     :
    - https://github.com/knik0/faad2/archive/2_9_2.tar.gz : 9728b2b94f94ab49363cd229e7377fbe6ef3c311c5cd80da662d53ddb0ee091d
homepage   : https://github.com/knik0/faad2/
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : Open source MPEG-2 and MPEG-4 AAC decoder
description: |
    Freeware Advanced Audio (AAC) Decoder is a HE, LC, MAIN and LTP
    profile, MPEG-2 and MPEG-4 AAC decoder. FAAD2 includes code for SBR
    (HE AAC) decoding.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install

